services:
  api:
    image: ghcr.io/lmaykot/gestaoesc-api:latest
    platform: linux/arm64
    ports:
      - "8000:8000"
    volumes:
      - db-data:/app/data
      - pdf-storage:/app/contratos
    environment:
      - DB_PATH=/app/data/gestao_contratos.db
      - CONTRATOS_DIR=/app/contratos

  frontend:
    image: ghcr.io/lmaykot/gestaoesc-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  db-data:
  pdf-storage:
